### ISSUE TITLE
《云计算系统》线下班 Assignment9 （截止时间5月12日）

### ISSUE THREAD

**Issue by TieWay59** [X-lab2017/oss101#119]
see: https://gitea.shuishan.net.cn/xslu_dase_ecnu_edu_cn/cloud-computing-course

**Comment by Bruce-Jay** [comment]
10205501411 bruce-jay.github.io

总结与反思：https://easonlin.blog/2023/04/28/BlogIntro/

**Comment by HdxL0V3** [comment]
学号：10205501405 博客：https://hdxl0v3.github.io/
本次作业总结：https://hdxl0v3.github.io/2023/04/28/%E4%BD%95%E5%BE%B7%E9%91%AB10205501405%E4%BA%91%E8%AE%A1%E7%AE%97lab9/

**Comment by XuDashuai0827** [comment]
10205501450  https://xudashuai0827.github.io/
总结与反思： https://xudashuai0827.github.io/2023-04-30-my-experiment/

**Comment by gloriaaa0312** [comment]
10205501437 https://gloriaaa0312.github.io/
总结与反思：https://gloriaaa0312.github.io/2023-04-30-Assignment9/

**Comment by wsy1114534906** [comment]
10205501429 https://wsy1114534906.github.io/
实验9：https://wsy1114534906.github.io/wangsiyuan.github.io/2023-05-02-problems/

**Comment by Silhouette0** [comment]
10205501416 https://silhouette0.github.io/
总结：https://silhouette0.github.io/%E6%80%BB%E7%BB%93&%E5%8F%8D%E6%80%9D.html

**Comment by Linshou99** [comment]
10205501409 https://linshou99.github.io/
总结与反思：https://linshou99.github.io/2023/05/04/%E6%80%BB%E7%BB%93%E4%B8%8E%E5%8F%8D%E6%80%9D/

**Comment by Boat2U** [comment]
10205501433 https://boat2u.github.io/
总结与反思：https://boat2u.github.io/2023/05/04/summary/

**Comment by duliaojason** [comment]
10205501457 duliaojason.github.io
总结与反思：duliaojason.github.io/2023/04/28/CloudComputing/

**Comment by duliaojason** [comment]
10205501457 [duliaojason.github.io](https://duliaojason.github.io/)
总结与反思：[duliaojason.github.io/2023/04/28/CloudComputing/](https://duliaojason.github.io/2023/04/28/CloudComputing/)

**Comment by toodeoo** [comment]
10205501439 https://toodeoo.github.io/
总结与反思：https://toodeoo.github.io/2023-05-04-report/

**Comment by myJisoo** [comment]
10205501436 https://myjisoo.github.io/
反思与总结 https://myjisoo.github.io/2023/05/05/%E5%8F%8D%E6%80%9D%E4%B8%8E%E6%80%BB%E7%BB%93/

**Comment by 10205501431** [comment]
10205501431 https://10205501431.github.io/
总结与反思： https://10205501431.github.io/2020-04-28-flake-it-till-you-make-it/

**Comment by PeterXu1209** [comment]
10205501440 徐沛楹： https://peterxu1209.github.io
总结与反思： https://peterxu1209.github.io/2023/05/05/反思与总结/

**Comment by Jiapang777777** [comment]
10205501403 https://jiapang777777.github.io/
总结与反思：https://jiapang777777.github.io//2023/05/05/%E6%80%BB%E7%BB%93%E4%B8%8E%E5%8F%8D%E6%80%9D/

**Comment by KennyGJOUK** [comment]
10194810401 https://kennygjouk.github.io
总结与反思 https://kennygjouk.github.io/posts/Report/

**Comment by TOMYUE** [comment]
10205501461 https://tomyue.github.io/first-blog/
总结与反思 https://tomyue.github.io/first-blog/posts/my-first-post/

**Comment by yuanam** [comment]
10205501404 https://yuanam.github.io/
总结与反思 https://yuanam.github.io/posts/%E5%BF%83%E5%BE%97/

**Comment by saulty-han** [comment]
10205501406 https://saulty-han.github.io/
总结与反思 https://saulty-han.github.io/2023/05/05/test/

**Comment by scraneg** [comment]
10205501422 https://scraneg.github.io/
总结与反思在博客主页

**Comment by melodrama04** [comment]
https://melodrama04.github.io/
总结与反思在主页

**Comment by Y-jiji** [comment]
10205501401 https://y-jiji.github.io/blog
总结和反思: https://y-jiji.github.io/blog/site/post.html?file=blog-from-scratch.md (原生html+js+css直接实现)

**Comment by LiXinyuan1015** [comment]
10205501425 https://lixinyuan1015.github.io/
总结与反思 https://lixinyuan1015.github.io/2023/05/07/%E6%80%BB%E7%BB%93/

**Comment by LiXinyuan1015** [comment]
10205501425 https://lixinyuan1015.github.io/
总结：https://lixinyuan1015.github.io/2023/05/07/Summary/

**Comment by XDxc-cuber** [comment]
10205501417 https://xdxc-cuber.github.io/
总结：https://xdxc-cuber.github.io/2023/05/06/%E6%80%BB%E7%BB%93%E5%92%8C%E6%84%9F%E6%82%9F/

**Comment by Christina327** [comment]
10194602473 https://christina327.github.io/
总结和反思: https://christina327.github.io/2023/05/07/hw9/

**Comment by Caroline-zou** [comment]
10205501402 https://caroline-zou.github.io/
总结和反思 https://caroline-zou.github.io/2023/05/02/cloud-computing-assignment9.html

**Comment by yan-mingyuan** [comment]
10190350440 https://yan-mingyuan.github.io/

**Comment by Zhangxixiang77** [comment]
10205510427 [https://zhangxixiang77.github.io/](url)
反思和总结 [https://zhangxixiang77.github.io/2023/05/08/MyFirstBlog/](url)

**Comment by Zhangxixiang77** [comment]
10205501427 [https://zhangxixiang77.github.io/](url)
反思和总结 [https://zhangxixiang77.github.io/2023/05/08/MyFirstBlog/](url)

**Comment by Zhangxixiang77** [comment]
10205501427 https://zhangxixiang77.github.io/
总结和反思 https://zhangxixiang77.github.io/2023/05/08/MyFirstBlog/

**Comment by ariahuang314** [comment]
11205501401 https://ariahuang314.github.io/blog.github.io/
总结与反思 https://ariahuang314.github.io/blog.github.io//2023/05/08/summary/

**Comment by NoSuger-p** [comment]
10205501456 https://nosuger-p.github.io/
总结与反思 https://nosuger-p.github.io/2023/05/08/cloud_computing-Assignment9/

**Comment by sunny-max-creater** [comment]
> see: https://gitea.shuishan.net.cn/xslu_dase_ecnu_edu_cn/cloud-computing-course

10205501455 https://sunny-max-creater.github.io/
总结与反思  https://sunny-max-creater.github.io/2023/05/08/My-First-Blog/

**Comment by mattian7** [comment]
10205501430 https://mattian7.github.io/
总结与反思 https://mattian7.github.io/2023/05/09/%E5%BB%BA%E7%AB%99%E8%AE%B0%E5%BD%95/

**Comment by ddding-z** [comment]
10193903447 https://ddding-z.github.io/
总结与反思 https://ddding-z.github.io/2023/05/08/Report/

**Comment by chengshenglin** [comment]
10205501434 https://chengshenglin.github.io/
反思与总结 https://chengshenglin.github.io/2023/05/09/%E4%BA%91%E8%AE%A1%E7%AE%97lab9%E5%8F%8D%E6%80%9D%E6%80%BB%E7%BB%93/

**Comment by BhJia** [comment]
10205501423 https://bhjia.github.io/
总结与反思 https://bhjia.github.io/2023/05/10/%E4%BA%91%E8%AE%A1%E7%AE%97Assignment9%E6%80%BB%E7%BB%93/

**Comment by blingber** [comment]
10205501411 https://blingber.github.io/

总结与反思：https://blingber.github.io/2023/05/10/myreport/

**Comment by Daserxqc** [comment]
10205501413 https://daserxqc.github.io/xqc.github.io/
总结： https://daserxqc.github.io/xqc.github.io/2023/05/09/summary/

**Comment by looper-sil** [comment]
10205501410 博客地址：[https://looper-sil.github.io/](https://looper-sil.github.io/)
                      [反思](https://looper-sil.github.io/2023/05/10/reflction.html)

**Comment by lvhaojia** [comment]
10205501414 https://lvhaojia.github.io/
总结与反思: https://lvhaojia.github.io/2023/05/10/%E6%80%BB%E7%BB%93%E4%B8%8E%E5%8F%8D%E6%80%9D.html

**Comment by siheyase** [comment]
10205501420 https://siheyase.github.io/yunjisuan/
总结：https://siheyase.github.io/yunjisuan/blog/post-record/

**Comment by lvhaojia** [comment]
10205501414 https://lvhaojia.github.io/
总结与反思 https://lvhaojia.github.io/2023/05/10/%E6%80%BB%E7%BB%93%E4%B8%8E%E5%8F%8D%E6%80%9D.html

**Comment by xuhuahuang813** [comment]
10205501424 https://xuhuahuang813.github.io/hxh_blog/
总结与反思 https://xuhuahuang813.github.io/hxh_blog/Summary

**Comment by DannieZhai** [comment]
10205501418 https://danniezhai.github.io/     
总结与反思：https://danniezhai.github.io/2020-02-28-test-markdown/

**Comment by lisiqi00** [comment]
10205501412 https://lisiqi00.github.io/
总结与反思：https://lisiqi00.github.io/2023/05/10/assignment9-report/

**Comment by 15110211** [comment]
10205501453 https://15110211.github.io/
总结与反思： https://15110211.github.io/summary/

**Comment by zhongershun** [comment]
10205501415 https://zhongershun.github.io/
总结与反思：https://zhongershun.github.io/2023/05/05/lab9_repo.html

**Comment by Breesiu** [comment]
10205501452 https://breesiu.github.io/
总结与反思：https://breesiu.github.io/2023/05/11/Assignment9总结

**Comment by Miaheeee** [comment]
10205501458 https://miaheeee.github.io/
总结与反思：https://miaheeee.github.io/2023/05/11/%E6%80%BB%E7%BB%93%E4%B8%8E%E5%8F%8D%E6%80%9D/

**Comment by xxxxxiwu** [comment]
10205501435 [https://xxxxxiwu.github.io](url)
反思与总结：[https://xxxxxiwu.github.io/2023/05/11/反思与总结/](url)

**Comment by shanhai222** [comment]
10205501407 https://shanhai222.github.io/
总结与反思：https://shanhai222.github.io/2023/05/05/%E5%8D%9A%E5%AE%A2%E5%88%B6%E4%BD%9C%E6%80%BB%E7%BB%93/

**Comment by ZhangChunXian** [comment]
10205501451 https://zhangchunxian.github.io/
总结与反思博客点进去首页就是

**Comment by zhuxiuw** [comment]
visit https://zhuxiuw.github.io to see my blog

**Comment by cc10205501438** [comment]
10205501438 https://cc10205501438.github.io/
首页就是总结与反思

**Comment by 10205501426** [comment]
10205501426 https://10205501426.github.io/
总结：https://redefine.ohevan.com/2023/05/12/总结/

**Comment by TieWay59** [comment]
统计：

```js
// 假设你的对象数组叫做 data
let regex = /(\d{11})/; // 匹配十一位的数字
let newArray = data.map(item => {
  let match = item.node.body.match(regex); // 尝试匹配十一位的数字
  if (match) { // 如果匹配成功
    return `${match[0]}\t${item.node.author.login}`; // 返回十一位的数字（学号）和 login，用 tab 分隔
  } else { // 如果匹配失败
    return `${item.node.author.login}\t${item.node.body}`; // 返回 login 和 body 的内容，用 tab 分隔
  }
});
newArray.sort(); // 对新数组进行排序
let newString = newArray.join("\n"); // 用换行符连接新数组的元素
console.log(newString); // 输出结果
```

表格：


> 两位同学格式不准确：
>
> melodrama04	https://melodrama04.github.io/
> 总结与反思在主页
> zhuxiuw	visit https://zhuxiuw.github.io to see my blog

<html>
<body>


学号 | id
-- | --
10190350440 | yan-mingyuan
10193903447 | ddding-z
10194602463 | zhuxiuw
10194602473 | Christina327
10194810401 | KennyGJOUK
10205501401 | Y-jiji
10205501402 | Caroline-zou
10205501403 | Jiapang777777
10205501404 | yuanam
10205501405 | HdxL0V3
10205501406 | saulty-han
10205501407 | shanhai222
10205501408 | melodrama04
10205501409 | Linshou99
10205501410 | looper-sil
10205501411 | Bruce-Jay
10205501411 | blingber
10205501412 | lisiqi00
10205501413 | Daserxqc
10205501414 | lvhaojia
10205501415 | zhongershun
10205501416 | Silhouette0
10205501417 | XDxc-cuber
10205501418 | DannieZhai
10205501419 | xbxj
10205501420 | siheyase
10205501422 | scraneg
10205501423 | BhJia
10205501424 | xuhuahuang813
10205501425 | LiXinyuan1015
10205501426 | 10205501426
10205501427 | Zhangxixiang77
10205501428 | 1hyJIN
10205501429 | wsy1114534906
10205501430 | mattian7
10205501431 | 10205501431
10205501433 | Boat2U
10205501434 | chengshenglin
10205501435 | xxxxxiwu
10205501436 | myJisoo
10205501437 | gloriaaa0312
10205501438 | cc10205501438
10205501439 | toodeoo
10205501440 | PeterXu1209
10205501450 | XuDashuai0827
10205501451 | ZhangChunXian
10205501452 | Breesiu
10205501453 | 15110211
10205501455 | sunny-max-creater
10205501456 | NoSuger-p
10205501457 | duliaojason
10205501458 | Miaheeee
10205501460 | dirtyDan0
10205501461 | TOMYUE
11205501401 | ariahuang314


</body>
</html>
