### ISSUE TITLE
[评价] 校内线下班的课程评价方式

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/oss101#21]
关于 2023 研究生开源课程的评价方式，总的来说：
- 课堂签到：10%
- 平时作业：30%
- 期中测试：10%
- 期末大作业：50%

具体方案可以参见：[语雀链接](https://xlab2017.yuque.com/staff-kbz9wp/ut3q7i/ynal465p346pha0m?singleDoc)

**Comment by will-ww** [comment]
第一周平时问答情况：

<div align=center>
<img src="https://user-images.githubusercontent.com/15010826/223012691-e24ad060-ef68-426f-b493-d5b167f7bd6b.png" width="350px">
</div>

**Comment by will-ww** [comment]
另外，特别鼓励大家最自己觉得好的答案**点赞**，不仅能够增加**回答人的贡献度**，还能够提升自己和高贡献度同学的关系连接，进而间接的提升**自己的贡献度**。这个也是 OpenRank 度量指标鼓励的价值导向。

![image](https://user-images.githubusercontent.com/15010826/223013155-79c2b345-1936-45d5-a754-61b71787d97a.png)

**Comment by GiveMeAnApple99** [comment]
> 关于 2023 研究生开源课程的评价方式，总的来说：
> 
> * 课堂签到：10%
> * 平时作业：30%
> * 期中测试：10%
> * 期末大作业：50%
> 
> 具体方案可以参见：[语雀链接](https://xlab2017.yuque.com/staff-kbz9wp/ut3q7i/ynal465p346pha0m?singleDoc)

老师，请问Project组队可以4个人吗

**Comment by will-ww** [comment]
> > 关于 2023 研究生开源课程的评价方式，总的来说：
> > 
> > * 课堂签到：10%
> > * 平时作业：30%
> > * 期中测试：10%
> > * 期末大作业：50%
> > 
> > 具体方案可以参见：[语雀链接](https://xlab2017.yuque.com/staff-kbz9wp/ut3q7i/ynal465p346pha0m?singleDoc)
> 
> 老师，请问Project组队可以4个人吗

最好三个，大赛我们也是准备按三个来的~

**Comment by GiveMeAnApple99** [comment]
> > > 关于 2023 研究生开源课程的评价方式，总的来说：
> > > 
> > > * 课堂签到：10%
> > > * 平时作业：30%
> > > * 期中测试：10%
> > > * 期末大作业：50%
> > > 
> > > 具体方案可以参见：[语雀链接](https://xlab2017.yuque.com/staff-kbz9wp/ut3q7i/ynal465p346pha0m?singleDoc)
> > 
> > 
> > 老师，请问Project组队可以4个人吗
> 
> 最好三个，大赛我们也是准备按三个来的~

收到，谢谢老师
