### ISSUE TITLE
oss101 本学期的 OpenRank 排名与课程综合成绩评价

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/oss101#290]
根据前面的[帖子](https://github.com/X-lab2017/oss101/issues/21)，我们做了下调整~

以 3、4、5 三个月作为主体过程，利用 OpenRank 对本学期课程的同学作为课程社区参与度与贡献度的量化依据，并以此作为最终课程评分的一部分。

- 出勤：10%
- 平时作业：30%
- 期中问答：10%
- OpenRank：10%
- 大作业：40%

**Comment by will-ww** [comment]
三次平时实践作业：
- https://github.com/X-lab2017/oss101/issues/33
- https://github.com/X-lab2017/oss101/issues/71
- https://github.com/X-lab2017/oss101/issues/139

**Comment by frank-zsy** [comment]
全学期 OSS101 课程 OpenRank 情况说明：

``` json

[{"name":"TieWay59","value":177.54},{"name":"will-ww","value":135.84},{"name":"zhicheng-ning","value":42.7},{"name":"DarkHighness","value":21},{"name":"Liuyushiii","value":17.96},{"name":"wengsy150943","value":15.19},{"name":"lroethan","value":14.51},{"name":"Hcque","value":14.02},{"name":"TengLuoLuo","value":13.63},{"name":"JinaoLiu","value":13.61},{"name":"TW-githubs","value":13.1},{"name":"Tamiflu233","value":12.33},{"name":"abcdabcd3899","value":12.33},{"name":"gongchenghua","value":11.66},{"name":"gqq1210","value":11.43},{"name":"yz2022","value":11.22},{"name":"nicole01101101zke","value":11},{"name":"Zzzzzhuzhiwei","value":10.8},{"name":"GiveMeAnApple99","value":10.09},{"name":"zzyzeyuan","value":9.81},{"name":"JinkaiXu","value":9.49},{"name":"PeterXu1209","value":9.44},{"name":"zhouchenyi2000","value":9.4},{"name":"yfsn666","value":9.2},{"name":"Jalingpp","value":8.72},{"name":"Yukiho1028","value":8.67},{"name":"heroding77","value":8.64},{"name":"andyhuang18","value":8.59},{"name":"yygs-yyss","value":8.39},{"name":"tennnx","value":8.19},{"name":"hzhang4433","value":8.11},{"name":"See-r","value":7.96},{"name":"qkgoalkeeper","value":7.65},{"name":"HunterHan","value":7.52},{"name":"Breesiu","value":6.87},{"name":"tyn1998","value":6.77},{"name":"xwyzsn","value":6.69},{"name":"springyulu","value":6.66},{"name":"itsKevin-lgy","value":6.65},{"name":"Skydzl","value":6.48},{"name":"lh123cha","value":5.96},{"name":"Miaheeee","value":5.78},{"name":"Kongbaimoon","value":5.61},{"name":"iclovemiku","value":5.6},{"name":"wj23027","value":5.41},{"name":"XDxc-cuber","value":5.29},{"name":"Freejww","value":5.16},{"name":"594Surefour","value":5.12},{"name":"Ashura5","value":5.08},{"name":"pourquoi-1130","value":4.9},{"name":"wujwyi","value":4.81},{"name":"Zhangxixiang77","value":4.8},{"name":"hyDududu","value":4.78},{"name":"Boat2U","value":4.68},{"name":"LinRS1999","value":4.65},{"name":"Christina327","value":4.64},{"name":"Goinggoinggoing","value":4.61},{"name":"stevending1st","value":4.51},{"name":"wangyu-ustc","value":4.5},{"name":"HEHEhe00","value":4.41},{"name":"EIPsilly","value":4.39},{"name":"lxr599","value":4.33},{"name":"HaoyangShi","value":4.23},{"name":"BhJia","value":4.16},{"name":"looper-sil","value":4.13},{"name":"lhbvvvvv","value":4.07},{"name":"qqliang","value":3.97},{"name":"Philosober","value":3.91},{"name":"Chastelovee","value":3.82},{"name":"10205501431","value":3.68},{"name":"bensonzxs","value":3.67},{"name":"rad9-13","value":3.52},{"name":"yyq08042","value":3.5},{"name":"RainforestC","value":3.42},{"name":"Y-jiji","value":3.41},{"name":"blingber","value":3.41},{"name":"tyxtyxtyxtyx","value":3.41},{"name":"EiJuynah","value":3.38},{"name":"xiaofeichong123","value":3.37},{"name":"JasonZhujp","value":3.36},{"name":"Curious-chen","value":3.26},{"name":"yuanam","value":3.19},{"name":"RTEnzyme","value":2.99},{"name":"Breaddsmall","value":2.97},{"name":"zhangbububu","value":2.94},{"name":"NoSuger-p","value":2.89},{"name":"WuDi329","value":2.8},{"name":"wypsz","value":2.68},{"name":"Beanm7","value":2.66},{"name":"tiertie","value":2.61},{"name":"innocentc","value":2.61},{"name":"xxxxxiwu","value":2.52},{"name":"scraneg","value":2.52},{"name":"ZhangChunXian","value":2.45},{"name":"xuhuahuang813","value":2.45},{"name":"mattian7","value":2.45},{"name":"tmyisgod","value":2.4},{"name":"Bruce-Jay","value":2.32},{"name":"Wxlhhh","value":2.3},{"name":"OSZhouYe","value":2.27},{"name":"likeChen129","value":2.23},{"name":"Aries-wy","value":2.21},{"name":"zhuxiuw","value":2.21},{"name":"10205501426","value":2.21},{"name":"tang-small-flower","value":1.9},{"name":"myJisoo","value":1.89},{"name":"momentNi","value":1.83},{"name":"Missjust","value":1.8},{"name":"chengshenglin","value":1.56},{"name":"AmbitionCX","value":1.47},{"name":"xunx911","value":1.31},{"name":"KAlbert2333","value":1.27},{"name":"Silhouette0","value":1.21},{"name":"ecnu-yzj","value":1.19},{"name":"XuDashuai0827","value":1.16},{"name":"gloriaaa0312","value":1.16},{"name":"HdxL0V3","value":1.16},{"name":"JackWeiw","value":1.15},{"name":"renrenyouyuyu","value":1.14},{"name":"iWYZ-666","value":1.02},{"name":"zhuangbiaowei","value":0.94},{"name":"lukefan","value":0.88},{"name":"lvhaojia","value":0.84},{"name":"duliaojason","value":0.84},{"name":"LiXinyuan1015","value":0.84},{"name":"yangjie407","value":0.77},{"name":"gdbaixuefeng","value":0.74},{"name":"1161295395","value":0.71},{"name":"Linshou99","value":0.71},{"name":"KennyGJOUK","value":0.71},{"name":"shanhai222","value":0.71},{"name":"Jiapang777777","value":0.71},{"name":"ariahuang314","value":0.71},{"name":"DannieZhai","value":0.71},{"name":"toodeoo","value":0.71},{"name":"lisiqi00","value":0.71},{"name":"Caroline-zou","value":0.71},{"name":"sunny-max-creater","value":0.71},{"name":"ddding-z","value":0.71},{"name":"siheyase","value":0.71},{"name":"melodrama04","value":0.71},{"name":"wsy1114534906","value":0.71},{"name":"saulty-han","value":0.71},{"name":"yan-mingyuan","value":0.71},{"name":"zhongershun","value":0.71},{"name":"Daserxqc","value":0.71},{"name":"cc10205501438","value":0.71},{"name":"15110211","value":0.71},{"name":"TOMYUE","value":0.71},{"name":"tc2000731","value":0.7},{"name":"Jolykkkk","value":0.65},{"name":"neolee","value":0.64},{"name":"YinZheng-Sun","value":0.61},{"name":"xiaoyujinghe","value":0.61},{"name":"caiwanli","value":0.61},{"name":"ifshine","value":0.61},{"name":"hsy77","value":0.59},{"name":"Wind-Gone","value":0.53},{"name":"smell-iron","value":0.51},{"name":"xgdyp","value":0.49},{"name":"frank-zsy","value":0.42},{"name":"AliceCodeZhang","value":0.39},{"name":"Dousir9","value":0.39}]
```

以上是该仓库 2 月至 5 月的 OpenRank 总和，目前一共有 163 个账号的信息，学生的最大值 21，最小值 0.39，可以考虑阶梯划分分段并设置分值。

**Comment by frank-zsy** [comment]
@TieWay59 我把账号和姓名对应了一下，签到 Issue 里只有 80 个左右账号，很多长尾的账号是没有对应姓名的，可能需要你人工对应一下，当然如果是分段的话，分数特别低的可能不需要完全对应到人。

[result.xlsx](https://github.com/X-lab2017/oss101/files/11795434/result.xlsx)

**Comment by will-ww** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>



DarkHighness | 21
-- | --
Liuyushiii | 17.96
wengsy150943 | 15.19
lroethan | 14.51
Hcque | 14.02
TengLuoLuo | 13.63
JinaoLiu | 13.61
TW-githubs | 13.1
Tamiflu233 | 12.33
abcdabcd3899 | 12.33
gongchenghua | 11.66
gqq1210 | 11.43
yz2022 | 11.22
nicole01101101zke | 11
Zzzzzhuzhiwei | 10.8
GiveMeAnApple99 | 10.09
zzyzeyuan | 9.81
JinkaiXu | 9.49
PeterXu1209 | 9.44
zhouchenyi2000 | 9.4
yfsn666 | 9.2
Jalingpp | 8.72
Yukiho1028 | 8.67
heroding77 | 8.64
andyhuang18 | 8.59
yygs-yyss | 8.39
tennnx | 8.19
hzhang4433 | 8.11
See-r | 7.96
qkgoalkeeper | 7.65
HunterHan | 7.52
Breesiu | 6.87
tyn1998 | 6.77
xwyzsn | 6.69
springyulu | 6.66
itsKevin-lgy | 6.65
Skydzl | 6.48
lh123cha | 5.96
Miaheeee | 5.78
Kongbaimoon | 5.61
iclovemiku | 5.6
wj23027 | 5.41
XDxc-cuber | 5.29
Freejww | 5.16
594Surefour | 5.12
Ashura5 | 5.08
pourquoi-1130 | 4.9
wujwyi | 4.81
Zhangxixiang77 | 4.8
hyDududu | 4.78
Boat2U | 4.68
LinRS1999 | 4.65
Christina327 | 4.64
Goinggoinggoing | 4.61
stevending1st | 4.51
wangyu-ustc | 4.5
HEHEhe00 | 4.41
EIPsilly | 4.39
lxr599 | 4.33
HaoyangShi | 4.23
BhJia | 4.16
looper-sil | 4.13
lhbvvvvv | 4.07
qqliang | 3.97
Philosober | 3.91
Chastelovee | 3.82
10205501431 | 3.68
bensonzxs | 3.67
rad9-13 | 3.52
yyq08042 | 3.5
RainforestC | 3.42
Y-jiji | 3.41
blingber | 3.41
tyxtyxtyxtyx | 3.41
EiJuynah | 3.38
xiaofeichong123 | 3.37
JasonZhujp | 3.36
Curious-chen | 3.26
yuanam | 3.19
RTEnzyme | 2.99
Breaddsmall | 2.97
zhangbububu | 2.94
NoSuger-p | 2.89
WuDi329 | 2.8
wypsz | 2.68
Beanm7 | 2.66
tiertie | 2.61
innocentc | 2.61
xxxxxiwu | 2.52
scraneg | 2.52
ZhangChunXian | 2.45
xuhuahuang813 | 2.45
mattian7 | 2.45
tmyisgod | 2.4
Bruce-Jay | 2.32
Wxlhhh | 2.3
OSZhouYe | 2.27
likeChen129 | 2.23
Aries-wy | 2.21
zhuxiuw | 2.21
10205501426 | 2.21
tang-small-flower | 1.9
myJisoo | 1.89
momentNi | 1.83
Missjust | 1.8
chengshenglin | 1.56
AmbitionCX | 1.47
xunx911 | 1.31
KAlbert2333 | 1.27
Silhouette0 | 1.21
ecnu-yzj | 1.19
XuDashuai0827 | 1.16
gloriaaa0312 | 1.16
HdxL0V3 | 1.16
JackWeiw | 1.15
renrenyouyuyu | 1.14
iWYZ-666 | 1.02
zhuangbiaowei | 0.94
lukefan | 0.88
lvhaojia | 0.84
duliaojason | 0.84
LiXinyuan1015 | 0.84
yangjie407 | 0.77
gdbaixuefeng | 0.74
1161295395 | 0.71
Linshou99 | 0.71
KennyGJOUK | 0.71
shanhai222 | 0.71
Jiapang777777 | 0.71
ariahuang314 | 0.71
DannieZhai | 0.71
toodeoo | 0.71
lisiqi00 | 0.71
Caroline-zou | 0.71
sunny-max-creater | 0.71
ddding-z | 0.71
siheyase | 0.71
melodrama04 | 0.71
wsy1114534906 | 0.71
saulty-han | 0.71
yan-mingyuan | 0.71
zhongershun | 0.71
Daserxqc | 0.71
cc10205501438 | 0.71
15110211 | 0.71
TOMYUE | 0.71
tc2000731 | 0.7
Jolykkkk | 0.65
neolee | 0.64
YinZheng-Sun | 0.61
xiaoyujinghe | 0.61
caiwanli | 0.61
ifshine | 0.61
hsy77 | 0.59
Wind-Gone | 0.53
smell-iron | 0.51
xgdyp | 0.49
frank-zsy | 0.42
AliceCodeZhang | 0.39
Dousir9 | 0.39



</body>

</html>
