### ISSUE TITLE
华东师范大学数据学院暑期夏令营实践项目提交地址

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/oss101#297]
根据暑期夏令营实践项目的要求，提交到本 Issue 下面~

提交格式为： <学校> <姓名> <链接> 
- 仓库地址
- 报告地址

例如：

华东师范大学 廖浩宇 https://twiliness.cloud/
- [仓库地址](https://github.com/DarkHighness/darkhighness.github.io)

- [报告地址](https://twiliness.cloud/2023/03/20/about-blog/)

**Comment by HdxL0V3** [comment]
华东师范大学 何德鑫 https://hdxl0v3.github.io/

- [仓库地址](https://github.com/HdxL0V3/HdxL0V3.github.io)
- [报告地址](https://hdxl0v3.github.io/2023/07/01/Introduction/)

**Comment by gloriaaa0312** [comment]
华东师范大学 方蕴仪 https://gloriaaa0312.github.io/

**Comment by gloriaaa0312** [comment]
华东师范大学 方蕴仪 https://gloriaaa0312.github.io/

**Comment by gloriaaa0312** [comment]
华东师范大学 方蕴仪 https://gloriaaa0312.github.io/

- [仓库地址](https://github.com/gloriaaa0312/gloriaaa0312.github.io)

- [报告地址](https://gloriaaa0312.github.io/2023-07-01-SummerCamp/)

**Comment by XuDashuai0827** [comment]
华东师范大学 许瑞琪 https://xudashuai0827.github.io/

- [仓库地址](https://github.com/XuDashuai0827/XuDashuai0827.github.io)

- [报告地址1](https://xudashuai0827.github.io/2023-07-02-summer/)

- [报告地址2](https://xudashuai0827.github.io/2023-04-30-my-experiment/)

**Comment by DhuShen** [comment]
东华大学 盛鼎 https://dhushen.github.io/

- [仓库地址](https://github.com/DhuShen/DhuShen.github.io)
- [报告地址](https://dhushen.github.io/2023/07/02/dase-work-concluaion/)

**Comment by Nemotte** [comment]
华东师范大学 金子龙 https://nemotte.github.io/

[仓库地址](https://github.com/Nemotte/nemotte.github.io)

[报告地址](https://nemotte.github.io/2023/07/04/DaSE%E6%9A%91%E6%9C%9F%E5%A4%8F%E4%BB%A4%E8%90%A5%E5%AE%9E%E8%B7%B5%E9%A1%B9%E7%9B%AE-%E5%9F%BA%E4%BA%8EGitHub%E7%9A%84%E5%8D%9A%E5%AE%A2%E7%BD%91%E7%AB%99/)

**Comment by wbh1765091327** [comment]
浙江工业大学 王博海  https://wbh1765091327.github.io/

[仓库地址](https://github.com/wbh1765091327/wbh1765091327.github.io)

[报告地址](https://wbh1765091327.github.io/2023/07/07/summarize/)

**Comment by wbh1765091327** [comment]
浙江工业大学 王博海 https://wbh1765091327.github.io/

- [仓库地址] (https://wbh1765091327.github.io/)

- [报告地址](https://wbh1765091327.github.io/2023/07/07/summarize/)

**Comment by wbh1765091327** [comment]
浙江工业大学 王博海 https://wbh1765091327.github.io/

- [仓库地址](https://github.com/wbh1765091327/wbh1765091327.github.io) 

- [报告地址](https://wbh1765091327.github.io/2023/07/07/summarize/)

**Comment by zyYao0720** [comment]
上海海洋大学 姚之远  https://zyyao0720.github.io/
* [仓库地址](https://github.com/zyYao0720/zyYao0720.github.io/tree/master)
* [报告地址](https://zyyao0720.github.io/2023/07/08/%E9%A1%B9%E7%9B%AE%E6%80%BB%E7%BB%93/)

**Comment by wangguijiepedeval** [comment]
中南大学 王贵杰 http://www.wgj.ink/

- [仓库地址](https://github.com/wangguijiepedeval/wangguijiepedeval.github.io)

- [报告地址](http://www.wgj.ink/2023/03/01/tutorials/%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2%E6%90%AD%E5%BB%BA/)

**Comment by atoposyz** [comment]
吉林大学 马永哲 [https://atoposyz.github.io](https://atoposyz.github.io/)
- [仓库地址](https://github.com/atoposyz/atoposyz.github.io)
- [报告地址](https://atoposyz.github.io/2023/07/08/website/)

**Comment by burnanananana** [comment]
吉林大学 李一晗 https://burnanananana.github.io

    ●[仓库地址](https://github.com/burnanananana/burnanananana.github.io)
    ●[报告地址](https://burnanananana.github.io/2023/07/09/introduction/l)

**Comment by burnanananana** [comment]
吉林大学  李一晗 https://burnanananana.github.io
[报告地址](https://burnanananana.github.io/2023/07/09/introduction/)

**Comment by burnanananana** [comment]
吉林大学   李一晗  https://burnanananana.github.io

 - [仓库地址](https://github.com/burnanananana/burnanananana.github.io)
 - [报告地址](https://burnanananana.github.io/2023/07/09/introduction)

**Comment by Linshou99** [comment]
华东师范大学  陈沁文  https://linshou99.github.io/
- [仓库地址](https://github.com/Linshou99/Linshou99.github.io)
- [报告地址](https://linshou99.github.io/2023/07/13/report/)

**Comment by Zc0812** [comment]
武汉工程大学 张超 https://zc0812.github.io/

[仓库地址](https://github.com/Zc0812/Zc0812.github.io)

[报告地址](https://zc0812.github.io/2023/07/13/encu_summercamp/)

**Comment by Miaheeee** [comment]
华东师范大学 何雨晴 https://miaheeee.github.io/


- [仓库地址](https://github.com/Miaheeee/Miaheeee.github.io)


- [报告地址](https://miaheeee.github.io/2023/07/14/%E6%80%BB%E7%BB%93%E4%B8%8E%E5%8F%8D%E6%80%9D/)

**Comment by Jiapang777777** [comment]
华东师范大学 刘佳凡 https://jiapang777777.github.io/

- [[仓库地址](https://github.com/Jiapang777777/Jiapang777777.github.io)](https://github.com/Jiapang777777/Jiapang777777.github.io)

- [[报告地址](https://jiapang777777.github.io//2023/07/12/%E6%9A%91%E6%9C%9F%E5%A4%8F%E4%BB%A4%E8%90%A5%E5%9F%BA%E4%BA%8E-GitHub-%E7%9A%84%E5%8D%9A%E5%AE%A2%E7%BD%91%E7%AB%99/)](https://jiapang777777.github.io//2023/07/12/%E6%9A%91%E6%9C%9F%E5%A4%8F%E4%BB%A4%E8%90%A5%E5%9F%BA%E4%BA%8E-GitHub-%E7%9A%84%E5%8D%9A%E5%AE%A2%E7%BD%91%E7%AB%99/)

**Comment by Jiapang777777** [comment]
华东师范大学 刘佳凡 https://jiapang777777.github.io/

- [仓库地址](https://github.com/Jiapang777777/Jiapang777777.github.io)

- [报告地址](https://jiapang777777.github.io//2023/07/12/%E6%9A%91%E6%9C%9F%E5%A4%8F%E4%BB%A4%E8%90%A5%E5%9F%BA%E4%BA%8E-GitHub-%E7%9A%84%E5%8D%9A%E5%AE%A2%E7%BD%91%E7%AB%99/)

**Comment by LiXinyuan1015** [comment]
华东师范大学 李昕原 https://lixinyuan1015.github.io/

[仓库地址](https://github.com/LiXinyuan1015/LiXinyuan1015.github.io)

[报告地址](https://lixinyuan1015.github.io/2023/05/07/Summary/)

**Comment by Boat2U** [comment]
华东师范大学 谭冰 https://boat2u.github.io/

- [仓库地址](https://github.com/Boat2U/Boat2U.github.io)
- [报告地址](https://boat2u.github.io/2023/05/04/summer_camp/)

**Comment by yuanam** [comment]
华东师范大学 经清源 https://yuanam.github.io/

- [仓库地址](https://github.com/yuanam/yuanam.github.io)
- [报告地址](https://yuanam.github.io/posts/博客优化/)

**Comment by Gmorning730** [comment]
桂林电子科技大学 贾茂宁 https://creteisland.netlify.app/
* [仓库地址](https://github.com/Gmorning730/Gmorning730.github.io)
* [报告地址](https://creteisland.netlify.app/2023/07/14/%E5%8F%8D%E6%80%9D%E4%B8%8E%E6%80%BB%E7%BB%93/)

**Comment by 15110211** [comment]
华东师范大学 谢林娜 https://15110211.github.io/

- [仓库地址](https://github.com/15110211/15110211.github.io)

- [报告地址](https://15110211.github.io/summary/)

**Comment by WangQianyu6** [comment]
浙江师范大学 王千予 https://wangqianyu6.github.io/

- [仓库地址](https://wangqianyu6.github.io/)

- [报告地址](https://wangqianyu6.github.io/posts/8e58660f.html)

**Comment by NoSuger-p** [comment]
华东师范大学 彭林航 https://nosuger-p.github.io/
- [仓库地址](https://github.com/NoSuger-p/NoSuger-p.github.io)
- [报告地址](https://nosuger-p.github.io/2023/07/15/%E6%95%B0%E6%8D%AE%E7%A7%91%E5%AD%A6%E4%B8%8E%E5%B7%A5%E7%A8%8B%E5%AD%A6%E9%99%A2%E6%9A%91%E6%9C%9F%E5%A4%8F%E4%BB%A4%E8%90%A5%E5%AE%9E%E8%B7%B5%E9%A1%B9%E7%9B%AE%20-%20%E5%9F%BA%20%E4%BA%8E%20GitHub%20%E7%9A%84%E5%8D%9A%E5%AE%A2%E7%BD%91%E7%AB%99/)

**Comment by lizhez** [comment]
山东大学 李哲 https://lizhez.github.io/

- [仓库地址](https://github.com/lizhez/lizhez.github.io)
- [报告地址](https://lizhez.github.io/huadongshifan.html)

**Comment by saulty-han** [comment]
华东师范大学 蔡季妍 https://saulty-han.github.io/

- [仓库地址](https://saulty-han.github.io/)
- [报告地址](https://saulty-han.github.io/2023/05/05/test/)

**Comment by sjvirhivy** [comment]
南京农业大学 杨文璟 https://sjvirhivy.github.io/
- [仓库地址](https://github.com/sjvirhivy/sjvirhivy.github.io)
- [报告地址](https://sjvirhivy.github.io//%E5%A4%8F%E4%BB%A4%E8%90%A5%E5%AE%9E%E8%B7%B5%E9%A1%B9%E7%9B%AE%E6%80%BB%E7%BB%93%E4%B8%8E%E5%8F%8D%E6%80%9D/)

**Comment by Yunqi-Fang** [comment]
大连理工大学 王硕 https://yunqi-fang.github.io/

* [仓库地址](https://github.com/Yunqi-Fang/Yunqi-Fang.github.io)
* [报告地址](https://yunqi-fang.github.io/2023/07/15/%E6%9C%AC%E6%AC%A1%E4%BD%9C%E4%B8%9A%E7%9A%84%E6%80%BB%E7%BB%93/)

**Comment by zjnys** [comment]
河南大学 张家宁 https://zjnys.github.io/

[仓库地址](https://github.com/zjnys/zjnys.github.io)

[报告地址](https://github.com/zjnys/zjnys.github.io)

**Comment by gyqtc** [comment]
安徽大学 顾羽桥 www.gyqtc.xyz

**Comment by will-ww** [comment]
> 安徽大学 顾羽桥 [www.gyqtc.xyz](http://www.gyqtc.xyz)

不完整，还需要有报告~ @gyqtc

**Comment by gyqtc** [comment]
对不起老师，下午的汇报我会解释，如果老师一定要求提交报告的话，我今晚补一份，您看可以嘛

学生：顾羽桥



---- 回复的原邮件 ----
| 发件人 | Will ***@***.***> |
| 日期 | 2023年07月18日 09:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [X-lab2017/oss101] 华东师范大学数据学院暑期夏令营实践项目提交地址 (Issue #297) |

安徽大学 顾羽桥 www.gyqtc.xyz

不完整，还需要有报告~ @gyqtc

**Comment by will-ww** [comment]
> 对不起老师，下午的汇报我会解释，如果老师一定要求提交报告的话，我今晚补一份，您看可以嘛

没问题的~
