### ISSUE TITLE
[feat] Hope to update the courseware of the last five lessons

### ISSUE THREAD

**Issue by Nliver** [X-lab2017/oss101#299]
I am reviewing this course recently. Is it convenient to update the courseware of sections 13, 14, 15, 16 and 17?
最近在复习本套课程，请问13、14、15、16、17这五节的课件方便更新么？

![image](https://github.com/X-lab2017/oss101/assets/34496563/69ac5e9c-2205-4252-9efa-cab121ec025c)

**Comment by will-ww** [comment]
Many thanks for your interesting，我们这个月就将这几讲的内容更新上去~
