### ISSUE TITLE
2024 春季学期期末大作业任务总览（7.31前完成）

### ISSUE THREAD

**Issue by PureNatural** [X-lab2017/oss101#305]
## 任务目录：

- [OpenDigger](https://github.com/X-lab2017/open-digger/issues?q=is%3Aissue+is%3Aopen+label%3A%22%F0%9F%8C%B1+Spring+2024+OSS+101%22)
- [HyperCRX](https://github.com/hypertrons/hypertrons-crx/labels/%F0%9F%8C%B1%20Spring%202024%20OSS%20101)
- [OpenPerf](https://github.com/X-lab2017/open-perf/labels/%F0%9F%8C%B1%20Spring%202024%20OSS%20101)
- [OpenLeaderboard](https://github.com/X-lab2017/open-leaderboard/labels/%F0%9F%8C%B1%20Spring%202024%20OSS%20101)

大家好，OSS101 课程 2024 春季学期期末大作业已经发布了。本次任务主要包含了 4 个开源项目：OpenDigger，HyperCRX，OpenPerf 和 OpenLeaderboard，共计 31 个任务供大家认领，需要大家组队完成。为了帮助大家了解并顺利的完成每个任务，我们对每个项目安排了导师，大家在开发的过程中遇到问题可以在各个任务对应的 Issue 下进行提问，我们强烈建议同学们在开发的协作过程中能够在 Issue  中积极地讨论，本次大作业有以下几个注意事项：

- OpenDigger、HyperCRX、OpenLeaderboard 三个项目下的任务组队人数最多 3 人，OpenPerf 任务组队人数最多 4 人；
- OpenDigge、HyperCRX、OpenLeaderboard 下的任务如果已经被某个队伍认领，则其他队伍不可重复认领；
- OpenPerf 下的每个任务可以被一到两个队伍认领，每个队伍各自完成任务即可；
- 本次作业需要在 **7 月 31 日**之前完成；
- 如果有小队需要更换任务，可以更换到还未被认领的任务中，需要按格式重新提交一条评论，请大家按需选择任务；
- 提交PR时，PR 标题参考 “【Task 1】 + PR 内容 ” ，如 “【Task 1】 Add the label data about AIGC” 以便我们快速 Review PR。

本次大作业将在此 Issue 中汇总信息，如果你想认领某个任务，请参考格式在此 Issue 下回复，任务认领后则添加组长姓名，先到先得。你可以通过下表，了解到每一个任务的认领情况。

回复的格式为：

【组长】：组长姓名

【项目】：你要选择的项目

【序号】：你选择的任务序号

【成员】：你小组的其他成员姓名

如：

【组长】：王五

【项目】：OpenPerf

【序号】：02

【成员】：张三、李四

## OpenDigger
导师：@frank-zsy @will-ww [Peng99999](https://github.com/Peng99999)
|  序号  |  任务 ISSUE  |  组长姓名 |
| ------- | ------- | ------- |
| 1  |  [Add the label data about AIGC](https://github.com/X-lab2017/open-digger/issues/1559)  |   |
| 2  |  [Design and implement a new metric](https://github.com/X-lab2017/open-digger/issues/1560)  |   |
| 3  | [ Interpretation of existing metrics](https://github.com/X-lab2017/open-digger/issues/1561) |  郭腾 |
| 4  |  [Mirror Source Management Tool](https://github.com/X-lab2017/open-digger/issues/1562) |  支家和 |
| 5  |  [Automatic label classification task based on machine/deep learning methods](https://github.com/X-lab2017/open-digger/issues/1563) | 麻瑞阳  |
| 6  |  [Data Insight Report or Visualization Work](https://github.com/X-lab2017/open-digger/issues/1564) | 施瑾睿  |
| 7  |  [Open source domain visualization dashboard ](https://github.com/X-lab2017/open-digger/issues/1565) | 庞瑞洋  |

## HyperCRX
导师： @tyn1998  @lhbvvvvv [wxharry](https://github.com/wxharry)
|  序号  |  任务 ISSUE  |  组长姓名 |
| ------- | ------- | ------- |
|  1 | [Refactor the existing multiple languages feature by adopting a third i18n library](https://github.com/hypertrons/hypertrons-crx/issues/805) | 魏永富  |
|  2 | [List all adjacent nodes of the hovered node in collaboration networks for quick reference](https://github.com/hypertrons/hypertrons-crx/issues/806) | 梅杰源  |
|  3 | [Display OpenDigger labels in the right of the repository header](https://github.com/hypertrons/hypertrons-crx/issues/807) | 侯婷  |
|  4 | [Circle of contributors](https://github.com/hypertrons/hypertrons-crx/issues/808) |  朱奕帆  |
|  5 | [Display Community OpenRank](https://github.com/hypertrons/hypertrons-crx/issues/809) |  徐梦滢 |
|  6 | [Display extra information from OpenDigger in the developer information hover card](https://github.com/hypertrons/hypertrons-crx/issues/810) | 游明东  |
|  7 | [Display the metric Active dates and times from OpenDigger](https://github.com/hypertrons/hypertrons-crx/issues/811) |   |
|  8 | [Obtain GitHub tokens to increase request limits](https://github.com/hypertrons/hypertrons-crx/issues/812) |  王硕  |
|  9 | [A mechanism to remotely disable broken features](https://github.com/hypertrons/hypertrons-crx/issues/813) |   |
|  10 | [Finish the Repository Collection feature](https://github.com/hypertrons/hypertrons-crx/issues/814) |   |

## OpenPerf
导师：  @PureNatural @bifenglin  @Zzzzzhuzhiwei
|  序号  |  任务 ISSUE  |  组长姓名 |
| ------- | ------- | ------- |
| 1  |  [Developer/Repository Recommendation Method Based on GitHub Collaboration Network](https://github.com/X-lab2017/open-perf/issues/57) |  邱钰莹  高洪帆  |
| 2  |  [Construction of an open-source community question-answering dataset and implementation of a question-answering model](https://github.com/X-lab2017/open-perf/issues/58) |  韩凡宇 童文平  |
| 3  |  [Construction of Dataset and Method Implementation for Named Entity Recognition in the Open Source Community](https://github.com/X-lab2017/open-perf/issues/59) |  郑逸潇  |
| 4  |  [Machine Learning-based Developer Geolocation Information Mining](https://github.com/X-lab2017/open-perf/issues/60) |  郑中正  |
| 5  |  [Research and Implementation of Multi-Label Classification Methods for GitHub Repositories](https://github.com/X-lab2017/open-perf/issues/61) |  杨新宇 李垫  |
| 6  |  [Open source repository collaboration network and npm artifact library dependency network mapping dataset](https://github.com/X-lab2017/open-perf/issues/62) |  张雯怡  |
| 7  |  [find the influential developers and repositories in Github open source community](https://github.com/X-lab2017/open-perf/issues/63) |  黄帆 徐涵钰  |
| 8  |  [Classification reasearch : the role of developer in Github open source community](https://github.com/X-lab2017/open-perf/issues/64) |   钟青松  冉又玮 |

## OpenLeaderboard
导师：@andyhuang18 @wj23027 
|  序号  |  任务 ISSUE  |  组长姓名 |
| ------- | ------- | ------- |
| 1  |  [Platform Switch for Gitee and Github Rankings](https://github.com/X-lab2017/open-leaderboard/issues/111) |  丁永亮  |
| 2  |  [Add Region-Specific Rankings](https://github.com/X-lab2017/open-leaderboard/issues/112) |  陆辰昊  |
| 3  |  [Add Domain-Specific and Foundation Rankings](https://github.com/X-lab2017/open-leaderboard/issues/113) |  汪小曼  |
| 4  |  [change overall board design](https://github.com/X-lab2017/open-leaderboard/issues/114) |  郑朴辰  |
| 5 |  [Change the method of loading new data from scrolling down and clicking to flipping pages](https://github.com/X-lab2017/open-leaderboard/issues/115) |  叶哲名  |
| 6  |  [Refactor the columns of the project and developer leaderboard](https://github.com/X-lab2017/open-leaderboard/issues/116) |  周伟  |

**Comment by taketaketakeru** [comment]
【组长】：魏永富

【项目】：HyperCRX

【序号】：01

【成员】：张滕雪、李志文

**Comment by elegaa** [comment]
【组长】：侯婷

【项目】：Display opendigger labels in the right of the repository header

【序号】：3

【成员】: 刁圆员，张偲欣

**Comment by ECNU-51265903094** [comment]
【组长】：丁永亮

【项目】：OpenLeaderBoard

【序号】：01

【成员】：杨贇、毕其功

**Comment by YeexiaoZheng** [comment]
【组长】：郑逸潇

【项目】：OpenPerf：Construction of Dataset and Method Implementation for Named Entity Recognition in the Open Source Community

【序号】：03

【成员】：徐啟航、甄逸飞

**Comment by huangfan0** [comment]
【组长】：黄帆

【项目】：OpenPerf

【序号】：07

【成员】：赵思嘉

**Comment by W1evy** [comment]
【组长】：杨新宇

【项目】：Openperf

【序号】：05

【成员】：杨洪宇、吴逸伟、吴泓宇

**Comment by beyond-mountains** [comment]
【组长】：麻瑞阳

【项目】：OpenDigger

【序号】：05

【成员】：马洋涛、曹品善

**Comment by ZhmYe** [comment]
【组长】：叶哲名

【项目】：OpenLeaderboard

【序号】：05

【成员】：韦俊宇

**Comment by Tenth-crew** [comment]
【组长】游明东
【项目】 HyperCRX
【序号】 06
【成员】 陈宇轩 郑子路

**Comment by HaopuDong** [comment]
【组长】陆辰昊
【项目】OpenLeaderboard
【序号】2
【成员】董昊朴

**Comment by xiaoAugenstern** [comment]
【组长】：汪小曼

【项目】：OpenLeaderboard

【序号】：03

【成员】：xmy

**Comment by xiaoAugenstern** [comment]
【组长】：汪小曼

【项目】：OpenLeaderboard

【序号】：03

【成员】：张晓潇

**Comment by lilian-r** [comment]
【组长】：徐涵钰

【项目】：OpenPerf

【序号】：07

【成员】：孙文文、任丽伊、廖欣

**Comment by Thrrreeee** [comment]
【组长】：施瑾睿

【项目】：OpenLeaderboard

【序号】：06

【成员】：洪小清、杨佳宁

**Comment by xiaoAugenstern** [comment]
【组长】：徐梦滢

【项目】：HyperCRX

【序号】：05

【成员】: 单佑婉弘

**Comment by MaxWeeeell** [comment]
【组长】：邱钰莹

【项目】：OpenPerf

【序号】：01

【成员】: 李北步、申屠琦超、黄姗姗

**Comment by PureNatural** [comment]
【组长】：韩凡宇

【项目】：OpenPerf

【序号】：02

【成员】：王衍童

**Comment by zzz-ovo** [comment]
【组长】：郑中正

【项目】：OpenPerf

【序号】：04

【成员】：郑中正、臧志阳

**Comment by 1120680244** [comment]
【组长】：张雯怡

【项目】：OpenPerf

【序号】：02

【成员】：胡思劼

**Comment by 1120680244** [comment]
【组长】：张雯怡

【项目】：OpenPerf

【序号】：08

【成员】：胡思劼

**Comment by ChloeWenyiZhang** [comment]
【组长】：张雯怡
【项目】：OpenPerf
【序号】：08
【成员】：胡思劼

**Comment by Ld151739500002** [comment]
【组长】：李垫

【项目】：OpenLeaderboard

【序号】：04

【成员】: 叶韩辉，张豈明，吴行健

**Comment by PureNatural** [comment]
@Ld151739500002 OpenLeaderboard的任务最多3人完成，需要移除1名成员

**Comment by pry666** [comment]
【组长】：庞瑞洋

【项目】：OpenDigger

【序号】：07

【成员】：王方正，赵奕轲

**Comment by Ld151739500002** [comment]
【组长】：李垫

【项目】：OpenLeaderboard

【序号】：04

【成员】: 叶韩辉，张豈明

**Comment by JiaheZhi** [comment]
【组长】：支家和

【项目】：OpenDigger

【序号】：04

【成员】：张一

**Comment by mooricAnna** [comment]
【组长】：高洪帆

【项目】：OpenPerf

【序号】：01

【成员】: 胡诗彦、徐榕荟、刘思聪

**Comment by Ld151739500002** [comment]
【组长】：李垫

【项目】：OpenPerf

【序号】：01

【成员】: 叶韩辉，张豈明，吴行健

【本条为任务与人员双修改】

**Comment by PureNatural** [comment]
@Ld151739500002 在你评论之前，OpenPerf-01已经被两个小组认领，你可以再看看OpenPerf的其他任务

**Comment by MarigWeizhi** [comment]
【组长】：周伟

【项目】：OpenLeaderboard

【序号】：06

【成员】:  冷宜隆

**Comment by wouldmm** [comment]
【组长】：梅杰源

【项目】：OpenDigger

【序号】：01

【成员】:   张馨元

**Comment by xxrelax** [comment]
【组长】：钟青松

【项目】：OpenDigger

【序号】：02

【成员】: 曾龙  樊亦文

**Comment by Mark-00z** [comment]
【组长】：郑朴辰

【项目】：OpenLeaderboard

【序号】：04

【成员】: 郑岩钰

**Comment by Jankeeeeee** [comment]
【组长】：朱奕帆

【项目】：HyperCRX

【序号】：04

【成员】：黄小鹏、王超亚

**Comment by woyaochimangguo** [comment]
【组长】：童文平

【项目】：OpenPerf

【序号】：02

【成员】：陈碟、裘盼佳

**Comment by ChloeWenyiZhang** [comment]
【组长】：张雯怡
【项目】：OpenPerf
【序号】：06
【成员】：胡思劼
【备注】：更换任务，原任务为 OpenPerf 08

**Comment by hzshou** [comment]
【组长】：冉又玮
【项目】：OpenPerf
【序号】：08
【成员】：寿泓柘、吉刘骏、崔仁静

**Comment by wouldmm** [comment]
【组长】：梅杰源

【项目】：HyperCRX

【序号】：02

【成员】：张馨元

【备注】：更换任务，原任务为 OpenDigger 01

**Comment by xiaoAugenstern** [comment]
【组长】：汪小曼

【项目】：OpenLeaderboard

【序号】：03

【成员】：张晓潇、张嘉睿
