### ISSUE TITLE
[Labeled data] 线下班 OpenSODA 挑战赛组队专用贴

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/oss101#42]
本课程与 [OpenSODA 大赛](https://xlab2017.yuque.com/staff-kbz9wp/olpzth/vgzgtua6h3n0n7et)联动，并已经正式启动了[报名工作](https://xlab2017.yuque.com/staff-kbz9wp/olpzth/ma124i0lhi45h8xq)。

为了更好针对本课程进行后续追踪与技术支持，请本课程（仅限于）组队同学将每只队伍信息在本仓库中登记，以便后续给大家评分。样例如下：

<table>
<tr>
	<td>队名
	<td>队长
	<td>队员2
	<td>队员3
	<td>队员4
<tr>
	<td>X-lab
	<td>@TieWay59
	<td>@zhicheng-ning
	<td>@tyn1998
	<td>@xgdyp
</table>

**Comment by HaoyangShi** [comment]
abcdefg @HaoyangShi @xiaoyujinghe @Missjust

**Comment by 594Surefour** [comment]
光速开发 @bensonzxs @594Surefour @gdbaixuefeng

**Comment by wengsy150943** [comment]
亦可赛艇 @wengsy150943 @qkgoalkeeper @YinZheng-Sun @lh123cha

**Comment by hyDududu** [comment]
有想法队    @hydududu  @ifshine  @hsy77

**Comment by springyulu** [comment]
队名 | 队长 | 队员2 | 队员3 
-- | -- | -- | -- 
ECNU小菜狗 | @springyulu | @momentNI | @SEUerwht

**Comment by Philosober** [comment]
| 队名         | 队长        | 队员1   | 队员2    | 队员3          |
| ------------ | ----------- | ------- | -------- | -------------- |
| Coming Soon~ | @Philosober | @tennnx | @xunx911 | @pourquoi-1130 |

**Comment by Tamiflu233** [comment]
DaSE马戏团 @tamiflu233 @WuDi329 @renrenyouyuyu @wujwyi

**Comment by gqq1210** [comment]
刚才在吃饭 @gqq1210 @GiveMeAnApple99 @See-r @RainforestC

**Comment by DarkHighness** [comment]
队名 | 队长 | 队员 1 | 队员 2 | 队员 3
-- | -- | -- | -- | --
SOLE 回收站 | @DarkHighness | @EiJuynah | @KAlbert2333 | @nicole01101101zke

**Comment by iclovemiku** [comment]
| 队名 | 队长| 队员1 |
| --- | --- | --- |
| T0 | @iclovemiku  | @Ashura5 |

**Comment by abcdabcd3899** [comment]
|  队名   | 队长  | 队员 1| 队员 2|
|  ----  | ----  | ---- |
| 动感光波 biubiubiu   | @tyxtyxtyxtyx |@Kongbaimoon |@abcdabcd3899|

**Comment by JinaoLiu** [comment]
<html>
  <body>


队名 | 队长 | 队员 1 | 队员 2
-- | -- | -- | --
309 | @JinaoLiu| @yygs-yyss |  @LinRS1999


</body>
</html>

**Comment by Yukiho1028** [comment]
|  队名   | 队长  |  队员1  |队员2  |
|  ----  | ----  | ---- | ----|
| 摸鱼的醇香土豆泥  | @Yukiho1028 | @yyq08042  | @rad9-13  |

**Comment by Jalingpp** [comment]
|  队名   | 队长  | 队员1 | 队员2|
|  ----  | ----  | ---- | ----|
| 就是组了个队 | @Jalingpp | @tang-small-flower | @zhouchenyi2000 |

**Comment by lroethan** [comment]
<html>
<body>


队名 | 队长 | 队员1
-- | -- | --
QueryOwls | @lroethan | @caiwanli


</body>
</html>

**Comment by TW-githubs** [comment]
木鱼醒悟 [@TW-githubs](https://github.com/TW-githubs) [@JinkaiXu](https://github.com/JinkaiXu) [@RTEnzyme](https://github.com/RTEnzyme) [@Wind-Gone](https://github.com/Wind-Gone)

**Comment by gongchenghua** [comment]
|  队名   | 队长  | 队员1  | 队员2  |
|  ----  | ----  |  ----  | ----  |
| Gama Lab  | @gongchenghua | @zzyzeyuan | @Chastelove |

**Comment by yfsn666** [comment]
| 队名    | 队长     | 队员1            | 队员2       |
| ------- | -------- | ---------------- | ----------- |
| LBJ2306 | @yfsn666 | @Goinggoinggoing | @smell-iron |

**Comment by Hcque** [comment]
<html>
<body>


队名 | 队长 | 队员1 | 队员2 | 队员3
-- | -- | -- | --
0308four | @Hcque| | 


</body>
</html>

**Comment by Hcque** [comment]
| 队名 | 队长 | 列3 |
|-----|-----|-----|
| 0308four  | @Hcque  | 3   |
| 4   | 5   | 6   |

**Comment by andyhuang18** [comment]
|  队名  | 队长   | 队员1|队员2|队员3|
| ------------- | ------------- | ------- | ----------- | ------- |
| ikun队  | @andyhuang18 | @Zzzzzhuzhiwei| @wj23027 | @lhbvvvvv |

**Comment by HunterHan** [comment]
| 队名 | 队长|
| ---- | ---- |
| Cool-Lab| @HunterHan|

**Comment by TengLuoLuo** [comment]
<html>
<body>


队名 | 队长 | 队员1
-- | -- | --
啊哈哈哈哈 | @TengLuoLuo  | @yz2022 


</body>
</html>
