### ISSUE TITLE
[Labeled data] 《云计算系统》线下班 OpenSODA 挑战赛大作业专用贴 

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/oss101#61]
《云计算系统》课程与 [OpenSODA 大赛](https://github.com/ECNU/OpenSODA)联动，将 OpenSODA 赛题作为《云计算系统》课程大作业，具体说明[参见这里](https://xlab2017.yuque.com/staff-kbz9wp/olpzth/bgi9yhx05glx4zqc?singleDoc#)。

为了更好针对本课程进行后续追踪与技术支持，请本课程（仅限于）同学完成初赛后，将报名信息在本仓库中登记，以便后续给大家技术支持与评分。样例如下：

<table>
<tr>
	<td>队名
	<td>队员
	<td>选题
	<td>是否完成初赛
<tr>
	<td>X-lab
	<td>@TieWay59
	<td>W2
	<td>是
</table>

**Comment by JinaoLiu** [comment]
<html>
<body>


队名 | 队员 | 选题 | 是否完成初赛
-- | -- | -- | --
ecnu_opendigger | @JinaoLiu @yygs-yyss @LinRS1999 | T1 | 是


</body>
</html>

**Comment by gqq1210** [comment]
|  队名   | 队员  |  选题   | 是否完成初赛  |
|  ----  | ----  |  ----   |  ----  |
| 刚才在吃饭 |  @gqq1210 @GiveMeAnApple99 @See-r @RainforestC |  W1  | 是  |
