### ISSUE TITLE
[Labeled data] 第一讲线下班正式学员签到专用贴

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/oss101#8]
本课程的学习过程将利用 OpenDigger 开源项目来辅助进行助教自动化统计工作，因此，需要所有参与学员把自己的 GitHub 账号标注到仓库中，因此你需要：

1. 如果还没有 GitHub 账号，请注册一个；
2. 到 OpenDigger 仓库下指定 Issue 上，登记你的姓名与 GitHub 账号
3. 登记链接：https://github.com/X-lab2017/open-digger/issues/1217

**Comment by wujwyi** [comment]
吴家仪 @wujwyi

**Comment by gongchenghua** [comment]
龚成华 @gongchenghua
